services:
  postgres:
    image: postgres:17
    container_name: toy-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toydb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d toydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend

    container_name: toy-backend

    ports:
      - "8003:8003"

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/toydb

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: toy-frontend

    ports:
      - "3002:3002"

    depends_on:
      - backend

    restart: unless-stopped

volumes:
  postgres_data:
